---
# defaults file for ansible-role-cuda
# By default gpu is False, set it to True on the gpu nodes in the hosts file

gpu: True
cuda_repo_url: "http://developer.download.nvidia.com/compute/cuda/repos/"
cuda_rpm_key_path: /etc/rpm/nvidia_packaging_key.asc
cuda_packages:
 - cuda
cuda_restart_node_on_install: True
cuda_init: True
cuda_init_restart_service: True
cuda_init_compute_mode: 3
cuda_init_persistence_mode: 1
cuda_gpu_name0: "/dev/nvidia0"
cuda_bash_profile: True
cuda_bash_path: "/usr/local/cuda/bin"
cuda_bash_ld_lib_path: "/usr/local/cuda/lib64"
cuda_bash_cuda_root: "/usr/local/cuda"
cuda_bash_cuda_inc_dir: "/usr/local/cuda/bin"
cuda_bash_cpath: "/usr/local/cuda/include"

# vim:ft=ansible:
